### ISSUE TITLE
.signature-filter og avatar-filter

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RBKweb-Forum-Suite#1]
Lagde en gang et Tampermokey-script som fjernet signatur-blokken fra postene til visse brukere.
Scriptet har gått tapt tror jeg, men det er i alle fall en idé til funksjonalitet som innimellom er kjekk å ha.

Kan kanskje også lag et avatar-filter om noen har en for annoying gifanim som avatar eller en avatar som laster for tregt e.l.

**Comment by havremunken** [comment]
Gode idéer!

Jeg har en liten tankebaby på gang rundt en form for innstillinger, hvor dette lett kunne vært med (litt skeptisk til å defaulte til å ta bort ting så tidlig i scriptets levetid). For å få til innstillinger må jeg bare få laget noe greier rundt popup-vinduer (tenkte å ha et slags delvis gjennomsiktig overlay over forumet), det bør ikke være vanskelig. Og så bør hotkeys være konfigurerbare... Det tar ikke slutt med det første.

Begynner med popup-vinduene og tar det derfra!

**Comment by havremunken** [comment]
Når jeg tenker meg om, akkurat avatarer kan jo lett blokkeres ved å legge til en knapp e.l. i UI, trenger ikke settings for å legge dem til block-lista, bare for å ta dem vekk igjen.

**Comment by larsjaas** [comment]
Regner med du også vil lage opsjon for tråd-filter for Resultattips-tråder. :)

**Comment by havremunken** [comment]
Hehe, njaaa, kanskje noe mer generelt. Det er jo ivaretatt med den andre
greia. Lager en "kanskje"-sak til jeg får god tid en dag.. ;)

2018-03-03 20:54 GMT+01:00 Lars J. Aas <notifications@github.com>:

**Comment by larsjaas** [comment]
Og denne.
